app/validators/string_format_validator.rb
test/string_format_assertions.rb
test/test_helper.rb
test/validators/string_format_validator_test.rb

There will be many validations required for various string formats, and as a result, there will be a lot of duplicate code.
Add a custom `StringFormatValidator` along with a custom assertion `assert_validates_format_rules` to use in model tests with those validations.
In use, you might have a test for a model `Foo` and want to check that certain validations exist on it's `:bar` property.
```ruby
class FooTest < ActiveSupport::TestCase
test 'bar attribute validates with the expected rules' do
expected_rules = [:starts_with_non_whitespace, :has_only_printable_characters]
assert_validates_format_rules expected_rules, Foo, :bar
end
end
```

Add StringFormatValidator and Test

---

app/models/game.rb
db/migrate/20170129233937_create_games.rb
db/schema.rb
test/models/game_test.rb

PR includes non-association properties `title`, and `description`.  Includes `Game` model, migration, unit tests, and updated schema.
___
related: https://github.com/allegroplanet/allegro-planet/issues/9

Add Game Model

---

app/models/game.rb
app/models/user.rb
db/migrate/20170224034506_create_games_users_join_table.rb
db/schema.rb
test/models/game_test.rb
test/models/user_test.rb

This PR adds a `has_and_belongs_to_many` association between `User` and `Game`.  Includes tests, migration on a join table.

Add User<->Game Association

---

app/controllers/games_controller.rb
app/models/game.rb
app/views/games/index.html.erb
config/routes.rb
db/migrate/20170225165641_add_slug_to_games.rb
db/schema.rb
test/controllers/games_controller_test.rb
test/fixtures/games.yml
test/models/game_test.rb

URLs currently use IDs to retrieve records:
`http://www.asdf.com/depot/games/1`
Instead, URLs should use the slug:
`http://www.asdf.com/depot/games/name-of-game`
- Add `slug` to `Game` (through the `games` table in the database)
- Add a path to `depot/games/:slug` so URLs can use the slug
- Require a unique game title (no duplicate titles or URLs or slugs)
___
/cc @amarillion 
___
/ fixes https://github.com/allegroplanet/allegro-planet/issues/16

Add slug to Game; Allow URL to 

---

app/models/game_file.rb
app/models/game_release.rb
app/uploaders/game_file_uploader.rb
config/initializers/rails_admin.rb
db/migrate/20170226080301_create_game_files.rb
db/migrate/20170226084857_add_game_release_reference_to_game_file.rb
db/schema.rb
test/models/game_file_test.rb
test/models/game_release_test.rb

This PR adds:
- A `GameFileUploader` that uploads files to S3 at `/game-files/game-filename.zip'
- `zip` files only
- Adds associations between `GameRelease` <-> `GameFile`

Add GameFiles

---

app/controllers/games_controller.rb
app/views/games/show.html.erb

On a game's page, it currently only show title, description, and screenshots.  There is no downloadable files or information about releases.
Add a very simple front-end to list release versions and the files associated with them.

Show releases and game files

---

app/models/game.rb
app/models/user.rb
app/views/games/index.html.erb
config/routes.rb
test/controllers/games_controller_test.rb
test/controllers/users_controller_test.rb

Prior to this PR, we would have to build paths to records manually, e.g. `depot/games/#{game.slug}`.  However, this is not ideal, as Rails has a convention that implicitly generates paths.
Add a `#to_param` method to `User` and `Game` that overrides the expected param to be used in the path.  Now paths can properly be automatically generated with the path helpers (`user_path`, `url_for`, etc.)
This will mean that paths for games will no longer be routed through the `/depot/games` path, and instead will be routed simply in `/games`.  I'm sure there is a way to change this without breaking the auto-generated paths (I like these being under `/depot`), but I'll leave that for later. 🙂

Improve path helpers

---

app/controllers/games_controller.rb
app/controllers/users_controller.rb
app/models/game.rb
app/models/user.rb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20170302062847_rename_game_slug_to_handle.rb
db/migrate/20170302063921_rename_user_slug_to_handle.rb
db/migrate/20170302064617_add_index_to_all_handles.rb
db/schema.rb
test/fixtures/games.yml
test/fixtures/users.yml
test/models/game_test.rb
test/models/user_test.rb

The name `slug` is mildly annoying, so I'm going to rename it to `handle`.  It's the part of the path that is used to identify records in the URL:
```
http://www.allegroplanet.com/games/this-last-part-is-the-handle
```
Rename it.  Also, this PR adds an index on the `handle`s for `User` and `Game` so lookup will be faster.

Rename slug to handle

---

app/models/game.rb
app/models/game_release.rb
app/validators/string_format_validator.rb
test/models/game_release_test.rb
test/models/game_test.rb
test/validators/string_format_validator_test.rb

When creating a `Game`, you [can not have newline characters in the description](https://cloud.githubusercontent.com/assets/772949/23580834/089b3070-00d7-11e7-9272-a0d56a215142.png).  Currently, the field only allows [printable ascii characters](http://web.itu.edu.tr/sgunduz/courses/mikroisl/ascii.html).
Create a new format in `StringFormatValidator` that allows printable characters and new lines.
In `StringFormatValidator`, `has_only_printable_characters` has been renamed to `only_printable_characters`.

Allow newlines in textareas

---

app/models/concerns/email_format.rb
app/models/concerns/string_format.rb
app/models/user.rb
app/validators/string_format_validator.rb
test/models/user_test.rb
test/validators/string_format_validator_test.rb

In the beginning, validations on the models were originally created using an `EmailFormat` concern and a `StringFormat` concern with regexes and messages.  Later, a custom validator, `StringFormatValidator`, was used that generates better error messages and is more developer-friendly.
However, there is still some usage of the older `EmailFormat` and `StringFormat` concerns.
Remove the `EmailFormat` and `StringFormat` and replace them with the new `StringFormatValidator`.
Two tangentially related things have been added/changed:
- The "at least one digit" requirement has been removed from `password`
- An new `:only_printable_characters` requirement has been added to `password`

Remove Legacy String Validation

---

app/validators/string_format_validator.rb
test/validators/string_format_validator_test.rb

Some editors (like rails admin) will return text fields with `\r\n` as newlines.  This is a problem since the `\r` character does not pass validation:
Rather than sanitize the input, allow the carriage return `\r`character to qualify as a newline character.

Allow carriage return "\r" character in text fields

---

app/models/user.rb
app/validators/string_format_validator.rb
test/models/user_test.rb
test/validators/string_format_validator_test.rb

Username formats are not very robust and allow for some weird names (e.g. `^&*]{`, or `_-~`).
Reduce the scope of characters and format that is allowed for a username by creating a new validation rule `:username_characters`.  Also an `:at_least_one_alphanumeric_character` rule was added as well.
[See this issue for a list of format requirements](https://github.com/allegroplanet/allegro-planet/issues/26).
/ fixes https://github.com/allegroplanet/allegro-planet/issues/26

Fix Username Format

---

app/controllers/games_controller.rb
app/decorators/game_release_decorator.rb
app/models/game_file.rb
app/models/game_screenshot.rb
app/views/games/show.html.erb
test/decorators/game_release_decorator_test.rb
test/fixtures/game_screenshots.yml
test/models/game_file_test.rb
test/models/game_screenshot_test.rb

For some reason, CarrierWave and S3 like to generate really nasty URLs that look like this:
```
https://allegro-planet.s3.amazonaws.com/screenshots/krampus_shot_3.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIB5BMVW4AB8A%9201456704%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20170305T055242Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=f4aeab5df7dba2a875b4c77ae8b99a9a32cc17ae9bbbd6ca1bc0
```
Clean up the URLs by adding a `#public_url` method directly on the models for `GameFile` and `GameScreenshot`.  Now URLs would look like this:
```
https://allegro-planet.s3.amazonaws.com/screenshots/krampus_shot_3.png
```

Cleanup s3 screenshot urls

---

app/converters/markdown_converter.rb
test/converters/markdown_converter_test.rb

Whenever the `MarkdownConverter` attempts to render content of a `nul` value, it raises an exception and prevents the page from rendering.
Update `MarkdownConverter` to render "blank" arguments into an empty string.

Allow MarkdownConverter to Work Even When Given Empty Values

---

app/models/user.rb
test/fixtures/users.yml
test/models/user_test.rb

An odd thing occurs when attempting to resave a `User` after pulling it from the database.  Validation on `password` fails:
This peculiarity happens because `has_secure_password` actually does the validation and presence checks for `password` when it automatically generates the value for `password_digest`.   However, after the `password_digest` is present, the `password` field is set to `nil`.  As a result, any custom validations added on the model for `password` will fail after that point since `password` is set to `nil`.  So in our case, it is ok to have a `nil` password after creation.
An article discussing the issue [can be found here](https://quickleft.com/blog/rails-tip-validating-users-with-has_secure_password/).
Add `allow_nil: true` to `User#password` validation.  Also, add tests …

Fix User Password Validation

---

app/converters/markdown_converter.rb
test/converters/markdown_converter_test.rb

Currently the `MarkdownConverter` permits inline HTML. This can be a problem and could allow a malicious user to embed `<script></script>` tags that will run when loading that user's page.  At worst, this opens up a vulnerability for cross-site scripting.
Configure the `MarkdownConverter` to escape HTML tags.  Add tests.

Safely escape inline HTML from Markdown

---

config/initializers/rails_admin.rb

When creating a new `Game`, the `handle` param is marked as "Required". This can be confusing because there is no actual text input field. And, the `handle` param is automatically generated anyway.
- Prevent the field from being shown when creating a new Game.
- Customize the "help" message in Rails Admin so it reads as "Automatically generated" rather than "Required."
____
fixes https://github.com/allegroplanet/allegro-planet/issues/43
cc @allefant

Improve admin hint on handle field when creating a Game

---

config/initializers/rails_admin.rb

A `GameFile` must belong to one of several categories:
```
['MacOS binary', 'Win binary', 'Linux binary', 'Data files', 'Source files', 'Other']
```
In admin you have to input this value into a text input field, and there is no clue that it must be one of the types.  Also, the error message only appears _after_ you upload the file.
Use a dropdown that lists only the allowed values.
___
fixes https://github.com/allegroplanet/allegro-planet/issues/42
cc @allefant

In Admin, configure GameFile category field as dropdown

---

app/controllers/games_controller.rb
app/models/game_screenshot.rb
app/uploaders/game_screenshot_uploader.rb
app/views/games/show.html.erb
test/models/game_screenshot_test.rb

Uploaded `GameScreenshots` are not standard sized.  Right now on the `GamesController#show` page, images are displayed at full resolution.
Enable CarrierWave to create "versions" of the screenshot on upload.  The versions are:
```
VERSION_FEATURE_SIZE = [640, 360] # 1/3 HD
VERSION_TILE_SIZE    = [320, 180] # 1/6 HD
VERSION_THUMB_SIZE   = [160, 90]  # 1/12 HD
```
Also, only show the `feature` version in `GameController#show`
`GameScreenshots` that have been uploaded already will need to be re-uploaded so they can be processed.
____
cc @allefant 
fixes https://github.com/allegroplanet/allegro-planet/issues/37

Image versions for game screenshots

---

app/assets/stylesheets/application.css.sass
app/views/games/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flickity.html.erb

In `GameController`'s show page, screenshots are simply placed on the page as image tags.  It's not a very user-friendly experience.
Use the [Flickity](http://flickity.metafizzy.co/) carousel to group multiple images into a single carousel.

Add flickity photo carousel

---

app/controllers/github_webhooks_controller.rb
app/models/github_webhook.rb
app/views/github_webhooks/index.html.erb
config/routes.rb
db/migrate/20171008153311_add_github_webhooks.rb
db/schema.rb
test/controllers/github_webhooks_controller_test.rb
test/fixtures/github_webhooks.yml
test/models/github_webhook_test.rb

In order for Allegro Planet to begin working toward advanced features like remote build and CI, it will need to have support webhooks from GitHub.
In this simplest iteration, I'll add an endpoint at `/github_webhooks` that will simply take whatever data is passed to it, and store it as a `GithubWebhook` record.  Later, we can figure out what features to extract, and what actions we want to take on it.  Note that this feature also does not yet provide any restrictions on a requester and can receive calls from anywhere, not just from GitHub.
See the [GitHub docs on creating a CI server](https://developer.github.com/v3/guides/building-a-ci-server/) for more detail.

Support GitHub Webhooks

---

app/controllers/github_webhooks_controller.rb
app/models/github_webhook.rb
app/views/github_webhooks/index.html.erb
app/views/github_webhooks/show.html.erb
config/routes.rb
test/controllers/github_webhooks_controller_test.rb
test/models/github_webhook_test.rb

GitHub Webhooks currently hit Allegro Planet and Planet responds with a 422.  This is due to a requirement on rails that controllers actions can only be called with an "authenticity token".  Since no token exists when a webhook hits, rails responds with an error.
Also, GitHub Webooks post a pretty large payload.  This means the length validation of a maximum length of 512 will not work with this property.  Also, rather than showing the payloads with each item on the index page, it's better to move them to a show page and reduce the footprint on the index page.

Allow Webhook Access

---

app/controllers/github_webhooks_controller.rb

Due [to the tutorial](https://developer.github.com/v3/guides/building-a-ci-server/), it was assumed the payload would be provided in `params[:payload]`.  However, it's actually in the body, which can be pulled from `request.raw_post`.
Related: https://github.com/allegroplanet/allegro-planet/pull/55, https://github.com/allegroplanet/allegro-planet/pull/56

Use Request Body as Param for Webhook Payload

---

app/models/article.rb
db/migrate/20191020182233_add_published_to_article.rb
db/schema.rb
test/fixtures/articles.yml
test/models/article_test.rb

Right now, any and all articles that exist in the database are subject to being displayed once the view and controller are created.
Add a `published` status.  This will allow authors to create "pending" articles, or allow admins to easily disable articles from public view.
* Also included, is a `published` _scope_ on the `Article` model.  This will more easily allow the filtering of `published` articles for views and other lists.
_________
This is actually part 4 of https://github.com/allegroplanet/allegro-planet/issues/63

Add Published Status to Article

---

app/models/article.rb
test/models/article_test.rb

Currently, it's not possible to set an article's `published` to `false`!  Because of the way Rails handles `presence` validations, a `false` value indicates to Rails that the value is not present.
To fix this, I'll replace the `presence: true` validation with a `inclusion: { in: [true, false]}`, along with an error message.  This will still prevent `nil` values from being permitted, as is indicated by an updated test.
_____
This is a fix to https://github.com/allegroplanet/allegro-planet/pull/65

Fix presence validation on boolean "published" for Article

---

app/assets/stylesheets/application.css.sass
app/controllers/articles_controller.rb
app/views/articles/index.html.erb
app/views/articles/show.html.erb
app/views/layouts/_navbar.html.erb
config/routes.rb
test/controllers/articles_controller_test.rb

This is part 2 of https://github.com/allegroplanet/allegro-planet/issues/63.  Currently, articles are only visible via the console.  They do not display anywhere on the website.
This PR adds the basic features for showing articles on Allegro Planet.
* A list of articles located at `/articles`
* Individual article routes are automatically generated based on title, and appear at paths like `/articles/title-of-the-article`
* Only published articles can be seen
* A new link to "Articles" is added in the navbar
* Minimal styling is included. (Essentially no front-end work is included in this PR.)

Add Articles Controller, Routes, and Basic Rendering

---

config/initializers/rails_admin.rb

Articles are listed and can be displayed on the web, but the only way to create them is by logging into the shell.
Add the model to the RailsAdmin config. For now, this will give admins access and they will be able to add/edit/create articles.
In the future, each user should have the ability to create articles (along with games and releases) through a dashboard, and should not be restricted to administrators.

Add "Article" Records in Admin
